[Settings]
ID = "girlscodelincoln.com"

[build]
  base = "src/"
  publish = "src/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://www.girlscodelincoln.org/*"
  to = "https://girlscodelincoln.org/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://www.girlscodelincoln.com/*"
  to = "https://girlscodelincoln.com/:splat"
  status = 302
  force = true
