[Settings]
ID = "girlscodelincoln.com"

[build]
  base = "src/"
  publish = "src/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://donate.girlscodelincoln.com/"
  to = "https://www.nfggive.com/guidestar/83-2522645"
  status = 301
[[redirects]]
  from = "https://merchandise.girlscodelincoln.com/"
  to = "https://teespring.com/stores/girlscodelincoln"
  status = 301
[[redirects]]
  from = "https://mailinglist.girlscodelincoln.com/"
  to = "https://mailchi.mp/97830933907d/signup"
  status = 301
