[Settings]
ID = "girlscodelincoln.com"

[build]
  base = "src/"
  publish = "src/"

[[redirects]]
  from = "https://donate.girlscodelincoln.com/"
  to = "https://givetolincoln.com/nonprofits/girls-code-lincoln"
  status = 301
[[redirects]]
  from = "https://merchandise.girlscodelincoln.com/"
  to = "https://teespring.com/stores/girlscodelincoln"
  status = 301
[[redirects]]
  from = "https://beanie.girlscodelincoln.com/"
  to = "https://www.eventbrite.com/e/build-a-beanie-workshop-registration-58594364321"
  status = 301
[[redirects]]
  from = "https://beanie.girlscodelincoln.com/code"
  to = "https://drive.google.com/drive/folders/1lL_ZoWaBMHY9fjOk86XfHTf0Cog14_Sg"
  status = 301
[[redirects]]
  from = "https://beanie.girlscodelincoln.com/docs"
  to = "https://drive.google.com/open?id=1ft5nF0yKWGYbaLSQmorOtaFMC9nX6kMTZrBiCdVqWcM"
  status = 301
