[Settings]
ID = "girlscodelincoln.com"

[build]
  base = "src/"
  publish = "src/"

[[redirects]]
  from = "https://donate.girlscodelincoln.com/"
  to = "https://www.gofundme.com/h9j5y-girls-code-lincoln/donate"
  status = 301
[[redirects]]
  from = "https://merchandise.girlscodelincoln.com/"
  to = "https://teespring.com/stores/girlscodelincoln"
  status = 301
[[redirects]]
  from = "https://beanie.girlscodelincoln.com/"
  to = "https://www.eventbrite.com/e/build-a-beanie-workshop-registration-57357514871"
  status = 301
[[redirects]]
  from = "https://beanie.girlscodelincoln.com/code"
  to = "https://drive.google.com/drive/folders/1lL_ZoWaBMHY9fjOk86XfHTf0Cog14_Sg"
  status = 301
