[Settings]
ID = "girlscodelincoln.com"

[build]
  base = "src/"
  publish = "src/"

[[redirects]]
  from = "https://lincolngirlswhocode.com"
  to = "https://girlscodelincoln.com"
  status = 301
[[redirects]]
  from = "https://lincolngirlsintech.com"
  to = "https://girlscodelincoln.com"
  status = 301
