[Settings]
ID = "girlscodelincoln.com"

[build]
  base = "src/"
  publish = "src/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://donate.girlscodelincoln.com/"
  to = "https://paypal.me/girlscodelincoln"
  status = 301
[[redirects]]
  from = "https://merchandise.girlscodelincoln.com/"
  to = "https://teespring.com/stores/girlscodelincoln"
  status = 301
[[redirects]]
  from = "https://beanie.girlscodelincoln.com/"
  to = "https://www.eventbrite.com/e/build-a-beanie-workshop-registration-58594364321"
  status = 301
[[redirects]]
  from = "https://beanie.girlscodelincoln.com/docs"
  to = "https://drive.google.com/open?id=1ft5nF0yKWGYbaLSQmorOtaFMC9nX6kMTZrBiCdVqWcM"
  status = 301
[[redirects]]
  from = "https://storytelling.girlscodelincoln.com/"
  to = "https://www.eventbrite.com/e/66705821909/"
  status = 301
